apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-app
  namespace: openshift-monitoring
spec:
  endpoints:
  - scheme: http
    port: http
  namespaceSelector:
    matchNames:
      - my-namespace
  selector:
    matchLabels:
       app: test-app
